version: '3.8'
services:
  mysql-backend-cashflow:
    image: mysql:8.0
    command: ['mysqld', '--default-authentication-plugin=mysql_native_password']
    #container_name: mysql_cashflow_app_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cashflow
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    volumes:
      - ./dbdata-backend-cashflow:/var/lib/mysql  
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
    deploy:
      replicas: 2
      placement:
        constraints: [ node.role == manager ]  

  app:
    #container_name: nestjs-app
    #build: .
    image: jonataserpa/cash-flow:v1
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      MYSQL_HOST: mysql-backend-cashflow
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: cashflow
      MYSQL_PORT: 3306
    depends_on:
      - mysql-backend-cashflow
    deploy:
      replicas: 2
      placement:
        constraints: [ node.role == manager ]  

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8888:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [ node.role == manager ]    

  #prisma_migrate:
  #  image: nestjs-app
  #  build: .
  #  volumes:
  #    - .:/app
  #  depends_on:
  #    - mysql-backend-cashflow
  #  command: npx prisma migrate dev --name migration-dinamic    

volumes:
  mysql-data:
