version: '3.8'
services:
  app:
    container_name: nestjs-app
    build: .
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: backend_thewayschool_app
    depends_on:
      - mysql-backend-thewayschool

  mysql-backend-thewayschool:
    image: mysql:8.0
    command: ['mysqld', '--default-authentication-plugin=mysql_native_password']
    container_name: backend_thewayschool_app_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend_thewayschool_app
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    volumes:
      - ./dbdata-backend-thewayschool:/var/lib/mysql  
    ports:
      - "3309:3306"
    cap_add:
      - SYS_NICE

volumes:
  mysql-data:
