version: '3.8'
services:
  app:
    container_name: nestjs-app
    build: .
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql-backend-cashflow
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: cashflow
    depends_on:
      - mysql-backend-cashflow

  mysql-backend-cashflow:
    image: mysql:8.0
    command: ['mysqld', '--default-authentication-plugin=mysql_native_password']
    container_name: backend_cashflow_app_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cashflow
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    volumes:
      - ./dbdata-backend-cashflow:/var/lib/mysql  
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE

volumes:
  mysql-data:
