export const BusinessHelper = {
  AGRICULTOR: 'Agricultor Familiar',
  ATACADISTA: 'Atacadista',
  CEASA: 'Ceasa',
  CONSUMIDOR_FINAL: 'Consumidor Final',
  COOPERTATIVA: 'Cooperativa Agrícola',
  DISTRIBUIDOR: 'Distribuidor',
  GOVERNO: 'Governo',
  INDUSTRIA: 'Indústria',
  MINI_MERCADO: 'Mini Mercado',
  RESTAURANTE: 'Bares e restaurantes ',
  PRODUTO_RURAL_1: 'Produtor rural de Grande Porte',
  PRODUTO_RURAL_2: 'Produtor rural de Médio Porte',
  PRODUTO_RURAL_3: 'Produtor rural de Pequeno Porte',
  REPRESENTANTE: 'Representante Comercial',
  SUPER_MERCADO_1: 'Supermercado grande porte ',
  SUPER_MERCADO_2: 'Supermercado médio porte',
  SUPER_MERCADO_3: 'Supermercado pequeno porte',
  OUTROS: 'Outros',
};
